//shared prefrence
String TOKEN = "TOKEN";

const String welcometxt = "Welcome to Favorito";

//data
String business_id = "";
String business_name = "";
String business_status = "";
String is_profile_completed = "";
String is_information_completed = "";
String is_phone_verified = "";
String is_email_verified = "";
String is_verified = "";
String check_ins = "";
String ratings = '0.0';
String catalogoues = "";
String orders = "";
String free_credit = "";
String paid_credit = "";
String photoUrl = "";
String welcometxt2 =
    "Now your business will be in your\nphone!. Now your business will be in \nyour phone!.NYou can grow your\nbusiness with this.";
String pleaseEnter = 'Please Enter';
String pleaseEnterValid = 'Please Enter Valid';
String waitlistSetting = "Waitlist Settings";
String waitlist = "Waitlist";
String appoinmentSettingtxt = "Appoinment Setting";
String donetxt = "Done";

String bookingSetting = "Booking Settings";
String loading = "Loading...";
String wentWrong = "Something went wrong..";
String businessInformation = "Business Information";
String hoursTitle1 = 'Existing Slots';
String hoursTitle2 = 'Add New Slots';
